#!perl
use v5.24.0;
use warnings;

use lib 'lib';

use IO::Async::Loop;
use IO::Async::Timer::Periodic;
use Net::Async::HTTP;
use Synergy::Channel::Slack;
use Synergy::EventHandler::Mux;
use Synergy::EventHandler::Echo;
use Synergy::Hub;
use Synergy::ReplyChannel::Stdout;
use Synergy::ReplyChannel::Slack;
use Synergy::UserDirectory;

use Synergy::External::Slack;

my $key = qx(cat ~/.jem.key);
chomp $key;

my $config = shift;

my $loop = IO::Async::Loop->new;
my $http = Net::Async::HTTP->new;
$loop->add($http);

my $slack = Synergy::External::Slack->new({
  loop => $loop,
  http => $http,
  api_key => $key,
});

my $slack_channel = Synergy::Channel::Slack->new({
  name  => 'slack_fm',
  slack => $slack,
});

my $synergy = Synergy::Hub->new({
  user_directory => Synergy::UserDirectory->new({ config_file => $config }),
  event_handler  => Synergy::EventHandler::Mux->new({
    event_handlers => [ Synergy::EventHandler::Echo->new ]
  }),
});

$synergy->register_channel($slack_channel);

$synergy->set_loop($loop);

$loop->run;
