#!perl
use v5.24.0;
use warnings;

use lib 'lib';

use IO::Async::Loop;
use IO::Async::Timer::Periodic;
use Synergy::Channel::Slack;
use Synergy::Reactor::SlackID;
use Synergy::Reactor::Echo;
use Synergy::Reactor::Clox;
use Synergy::Reactor::LiquidPlanner;
use Synergy::Hub;
use Synergy::UserDirectory;

use Synergy::External::Slack;

my $key = qx(cat ~/.jem.key);
chomp $key;

my $loop = IO::Async::Loop->new;

my $slack_channel = Synergy::Channel::Slack->new({
  name  => 'slack_fm',
  api_key => $key,
});

my $synergy = Synergy::Hub->new({
  user_directory => Synergy::UserDirectory->new,
});

$synergy->register_reactor($_->new) for qw(
  Synergy::Reactor::Clox
  Synergy::Reactor::Echo
  Synergy::Reactor::LiquidPlanner
  Synergy::Reactor::SlackID
);

$synergy->register_channel($slack_channel);

$synergy->set_loop($loop);

if ($ENV{SYNERGY_USERS_FILE}) {
  $synergy->user_directory->load_users_from_file(
    $ENV{SYNERGY_USERS_FILE}
  );
}

$loop->run;
