#!perl
use v5.24.0;
use warnings;

use lib 'lib';

use IO::Async::Loop;
use IO::Async::Timer::Periodic;
use Net::Async::HTTP;
use Synergy::Event;
use Synergy::EventHandler::Mux;
use Synergy::EventHandler::Slack;
use Synergy::EventSource::Slack;
use Synergy::ReplyChannel::Stdout;
use Synergy::ReplyChannel::Slack;

use Synergy::External::Slack;

my $key = qx(cat ~/.jem.key);
chomp $key;

my $loop = IO::Async::Loop->new;
my $http = Net::Async::HTTP->new;
$loop->add($http);

my $slack = Synergy::External::Slack->new({
  loop => $loop,
  http => $http,
  api_key => $key,
});

my $eh = Synergy::EventHandler::Mux->new({
  eventhandlers => [
    Synergy::EventHandler::Slack->new({ slack => $slack }),
  ]
});


Synergy::EventSource::Slack->new({
  loop => $loop,
  eventhandler => $eh,
  slack => $slack,
});


$loop->run;
